---
title: "Finance Tools D"
author: "TJC"
date: "2023-01-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}

#See https://www.rpubs.com/AurelliaChristie/time-series-and-stock-analysis for 
#additional info. 

##attach libraries

#install.packages("quantmod")
install.packages("highcharter")

library(quantmod)
library(highcharter)

```


```{r get_prices}

price_bbri <- getSymbols("BBRI.JK", auto.assign=FALSE, from="2019-01-01", to="2022-12-31")

head(price_bbri)

```

```{r plot01}

# static plot
# Candle stick chart
chartSeries(price_bbri, name = "BBRI Price 2014-2019")

```

```{r plot02}

# Take only the closing price
closing_pr <- Cl(to.monthly(price_bbri))

# Decompose it
dc <- decompose(as.ts(closing_pr, start=c(2014,1)))
plot(dc)

# Seasonal component 
dc$seasonal

```

```{r plot03}

#interactive plot
#uses library(highcharter) - already installed and added above

highchart(type="stock") %>% 
  hc_add_series(price_bbri) %>% 
  hc_add_series(SMA(na.omit(Cl(price_bbri)),n=50),name="SMA(50)") %>% 
  hc_add_series(SMA(na.omit(Cl(price_bbri)),n=200),name="SMA(200)") %>% 
  hc_title(text="<b>BBRI Price Candle Stick Chart 2014-2019</b>")

```

```{r plot04}

#compares stocks within a sector

# Fetch BBNI, BMRI, and IHSG stock prices
price_bbni <- getSymbols("BBNI.JK",auto.assign=FALSE,from="2014-01-01",to="2019-12-31")
price_bmri <- getSymbols("BMRI.JK",auto.assign=FALSE,from="2014-01-01",to="2019-12-31")
price_ihsg <- getSymbols("^JKSE",auto.assign=FALSE,from="2014-01-01",to="2019-12-31")

# Compare the stock prices
highchart(type="stock") %>% 
  hc_add_series(Cl(price_bbri), name="BBRI") %>% 
  hc_add_series(Cl(price_bbni), name="BBNI") %>% 
  hc_add_series(Cl(price_bmri), name="BMRI") %>% 
  hc_add_series(Cl(price_ihsg), name="IHSG") %>% 
  hc_title(text="<b>BBRI vs BBNI vs BMRI vs IHSG Closing Price</b>")

```

```{r stock_return_analysis}

# Calculate the stocks return
return_bbri <- dailyReturn(Cl(price_bbri))
return_bbni <- dailyReturn(Cl(price_bbni))
return_bmri <- dailyReturn(Cl(price_bmri))

# Combine the returns as one data frame
returns <- data.frame(return_bbri,return_bbni,return_bmri)
names(returns) <- c("return_bbri","return_bbni","return_bmri")
returns <- as.xts(returns)

# Plot the returns
library(PerformanceAnalytics)
charts.PerformanceSummary(returns,main="Daily Return BBRI vs BBNI vs BMRI 2014-2019")

```





