---
title: "Utilities02"
author: "TJC"
date: "2023-01-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r libraries}

#install.packages("tidyquant")
library(tidyquant)      #tidyquant includes quantmod

#read excel file into r
#install.packages(readxl)
library(readxl)

#write to excel 
#install.packages("writexl")
library(writexl)

#get stock / commodity price data
library(quantmod)


#plotting
library(ggplot2)
library(gridExtra) # grid.arrange

```

```{r dates}

#use sys.Date to set start & end dates

date.start <- Sys.Date()-60
date.end <- Sys.Date()


```

```{r working_directory}

#working directory
setwd('C:/Users/tcoll/OneDrive/Github/Intro to Finance')     #set working directory

getwd()                         #show working directory

```

```{r excel}

#read excel file into r
#install.packages(readxl)
library(readxl)

read_excel("iris.xlsx") 

#--------------------------------------------------

#write to excel 
#install.packages("writexl")
library(writexl)
write_xlsx(iris, "iris.xlsx")
write_xlsx(aapl_prices,"aapl.xlsx")

#--------------------------------------------------
#example
#read ticker list - crude oil

CL_tickers <- read_excel("Tickers.xlsx","Tickers", col_types = NULL, range = "A1:A12", trim_ws = TRUE)


```

```{r stock_data}

library(quantmod)
goog_price <- getSymbols("GOOG", auto.assign=FALSE, from=date.start, to=date.end)
head(goog_price)

# Typically use previous value for NA
no.na <- which(is.na(goog_price[,6]))      # no for NA
goog_price[no.na,6] <- goog_price[no.na-1,6]
 
#-------------------------------------

#commodity
price_CLH23 <- getSymbols("CLH23.NYM", auto.assign=FALSE, from=date.start, to=date.end)
head(price_CLH23)

# Typically use previous value for NA
#no.na <- which(is.na(price_CLH23[,6]))      # no for NA
#price_CLH23[no.na,6] <- price_CLH23[no.na-1,6]
 
#-------------------------------------

#get attributes of the price data element
#class(goog_price)
#return is "xts" "zoo"      xts is extensible time series

```

```{r stock_data_01}

#https://www.r-bloggers.com/2021/05/retrieving-stock-price-using-r/

library(ggplot2)
library(gridExtra) # grid.arrange

#Setup
#graphics.off()
#rm(list=ls())

# Only stock price
goog_Close <- goog_price[,6]
#clh23_Close <- price_CLH23[,6]

# log return using adjusted stock price
goog_rtn <- diff(log(goog_price),1)

 
```

```{r stock_data_02}

#https://www.codingfinance.com/post/2018-03-27-download-price/
#getting stock data using tidyquant
library(tidyquant)

#download prices for a symbol
#this method assigns the object name as the ticker (auto.assign - TRUE)
options("getSymbols.warning4.0"=FALSE)
options("getSymbols.yahoo.warning"=FALSE)
# Downloading Apple price using quantmod

getSymbols("AAPL", from = '2021-01-01',
           to = "2022-03-01",warnings = FALSE,
           auto.assign = TRUE)
#head(AAPL)
#class(AAPL)

chart_Series(AAPL)

#zoom in to a certain date range

chart_Series(AAPL['2021-12/2022-03'])   #date range specified

#to get data for several tickers
tickers = c("IBM", "NFLX", "AMZN", "K", "F")

getSymbols(tickers,
           from = date.start,
           to = date.end)

prices <- map(tickers,function(x) Ad(get(x)))
prices <- reduce(prices,merge)
colnames(prices) <- tickers

```

```{r stock_data_03}

#https://www.codingfinance.com/post/2018-03-27-download-price/
#uses tidyquant
library(tidyquant)
#install.packages("tidyverse")
#library(tidyverse)
#install.packages(dplyr)
library(dplyr)
#install.packages("ggplot2")
library(ggplot2)
library(quantmod)

gs <- tq_get('GS',
               from = date.start,
               to = date.end,
               get = "stock.prices")

#head(GS)
#class(GS) #the object is a tibble - not a tsx

#gs %>%
#  ggplot(aes(x = date, y = adjusted)) +
#  geom_line() +
#  theme_classic() +
#  labs(x = 'Date',
#       y = "Adjusted Price",
#       title = "GS price chart") +
#  scale_y_continuous(breaks = seq(0,300,10))

#get data for multiple tickers
tickers = c("AAPL", "NFLX", "AMZN", "K", "O")

prices <- tq_get(tickers,
                 from = date.start,
                 to = date.end,
                 get = "stock.prices")

#head(prices)

#the tibble data stacks the symbols on top of each other
#the data has to be sliced to see the first row for each ticker
prices %>%
  group_by(symbol) %>%
  slice_head(n=1)

#chart the time series of all the prices
prices %>%
  ggplot(aes(x = date, y = adjusted, color = symbol)) +
  geom_line()
#this chart needs to be scaled for the different price levels
prices %>%
  ggplot(aes(x = date, y = adjusted, color = symbol)) +
  geom_line() +
  facet_wrap(~symbol,scales = 'free_y') +
  theme_classic() +
  labs(x = 'Date',
       y = "Adjusted Price",
       title = "Price Chart") +
  scale_x_date(date_breaks = "month",
               date_labels = "%b\n%y")

```

```{r index_data}

#library(tidyquant)

#https://business-science.github.io/tidyquant/articles/TQ01-core-functions-in-tidyquant.html

#list of indexes
tq_index_options()

#get index constituents and descriptive info
tq_index("SP500")

#get quantitative data
#data sources are:
  #Yahoo Finance - Daily stock data
  #FRED - Economic data
  #Quandl - Economic, Energy, & Financial Data API
  #Tiingo - Financial API with sub-daily stock data and crypto-currency
  #Alpha Vantage - Financial API with sub-daily, ForEx, and crypto-currency data
  #Bloomberg - Financial API. Paid account is required.

#see full list
tq_get_options()

#yahoo finance stock data (tibble) - date format is "YYYY-MM-DD" 
aapl_prices  <- tq_get("AAPL", get = "stock.prices", from = date.start)
aapl_prices 

#yahoo Japan stock prices - get = "stock.prices.japan"
#x8411T <- tq_get("8411.T", get = "stock.prices.japan", from = "2022-01-01", to  = "2022-12-31")

#---------------------------------------------------------

#FRED Economic Data
#data categories: https://fred.stlouisfed.org/categories
#WTI Crude Oil Prices
wti_price_usd <- tq_get("DCOILWTICO", get = "economic.data")
wti_price_usd 

#---------------------------------------------------------

#Tiingo API
#https://www.tiingo.com/
#The Tiingo API is a free source for stock prices, cryptocurrencies, and intraday feeds from the IEX (Investors Exchange). This can serve as an alternate source of data to Yahoo! Finance

library(tidyquant)
#install.packages("tidyverse")
library(tidyverse)

#authentication
tiingo_api_key('d67ad8ac8e8fa4fdba7cdad1edc90c12d64b7241')

#getting Tiingo data
#tidyquant package provides wrappers to the riingo package (R interface to Tiingo)
#examples:
# Tiingo Prices (Free alternative to Yahoo Finance!)

tq_get(c("AAPL", "GOOG"), get = "tiingo", from = "2023-01-01")

# Sub-daily prices from IEX ----
tq_get(c("AAPL", "GOOG"),
       get = "tiingo.iex",
       from   = "2020-01-01",
       to     = "2020-01-15",
       resample_frequency = "5min")

# Tiingo Bitcoin in USD ----
tq_get(c("btcusd"),
       get    = "tiingo.crypto",
       from   = "2020-01-01",
       to     = "2020-01-15",
       resample_frequency = "5min")

#---------------------------------------------------------

#Alpha Vantage API
#https://www.alphavantage.co/
#Authentication
av_api_key("7YSRPK7OQG6U1G5I")

```


```{r batch_get_symbols}

#libraries
#install.packages('BatchGetSymbols')
#install.packages('rvest')
#install.packages('dplyr')
#install.packages('yfR')

library(BatchGetSymbols)
library(rvest)
library(dplyr)
library("yfR")

# set dates
first.date <- Sys.Date() - 60
last.date <- Sys.Date()
freq.data <- 'daily'
# set tickers
tickers <- c('CLH23.NYM','CLK23.NYMM','CLM23.NYM','CLN23.NYM')

l.out <- BatchGetSymbols(tickers = tickers, 
                         first.date = first.date,
                         last.date = last.date, 
                         freq.data = freq.data,
                         cache.folder = file.path(tempdir(), 
                                                  'BGS_Cache') ) # cache in tempdir()

print(l.out$df.control)

library(ggplot2)
 
p <- ggplot(l.out$df.tickers, aes(x = ref.date, y = price.close))
p <- p + geom_line()
p <- p + facet_wrap(~ticker, scales = 'free_y') 
print(p)

```



